routes/web.php
<?php

use App\Http\Controllers\AdminHomeController;
use App\Http\Controllers\AssignUserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/login');
})->middleware(['auth']);

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    // dashboard routes
    Route::resource('/', AdminHomeController::class)->name('*', 'dashboard');

    // projects routes
    Route::resource('/projects', ProjectController::class)->name('*', 'projects');

    // projects category routes
    Route::resource('/categories', CategoryController::class)->name('*', 'categories');

    // users routes
    Route::resource('/users', UserController::class)->name('*', 'users');

    // profile routes
    Route::get('/profile', function () {return view('welcome');})->name('Profile');
});

Route::group(['prefix' => '', 'middleware' => ['auth', 'user']], function () {

    // dashboard routes
    Route::resource('/home', HomeController::class)->name('*', 'home');

    // user routes
    Route::resource('/user', UserController::class)->name('*', 'user');

    // projects routes
    Route::resource('/my/project', ProjectController::class)->name('*', 'project');

    // projects category routes
    Route::resource('/assign', AssignUserController::class)->middleware(['auth'])->name('*', 'assign');
});

require __DIR__ . '/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/admin/category_form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Settings') }}
        </h2>
    </x-slot>

    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="border-t-4 border-teal-500 rounded-b px-4 py-3 shadow-md bg-red-500 text-white absolute z-50" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Error</p>
                    <p class="text-sm">{{$error}}</p>
                </div>
            </div>
        </div>
        @endforeach
    @endif

    @if(Session::has('success'))
        <div class="border-t-4 border-teal-500 rounded-b px-4 py-3 shadow-md bg-green-500 text-white absolute z-50" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Success</p>
                    <p class="text-sm">{{session('success')}}</p>
                </div>
            </div>
        </div>
    @endif

    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 mt-5">
        <div class="md:grid md:grid-cols-3 gap-4">
            <div class="md:col-span-1">
                <div class="bg-blue-500 overflow-hidden shadow-md sm:rounded-md">
                    <div class="pt-8 pb-4 bg-blue-500 border-b border-gray-200">
                        <div class="px-4 sm:px-0">
                            <h3 class="block mx-4 font-semibold text-lg text-white">All Categories</h3>
                            <div class="mt-2 flex rounded-md shadow-sm mx-4">
                                <input type="text" name="search" class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded-none rounded-l-md sm:text-sm border-gray-300" placeholder="search...">
                                <button type="submit" class="inline-flex items-center px-3 rounded-r-md border border-l-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
                                    search
                                </button>
                            </div>
                            <div class="mt-2 text-sm text-gray-600" style="height: 420px; overflow-y: schroll;">

                                <ul class="divide-y divide-gray-100">
                                    @foreach($all_categories as $category)
                                        <li class="px-4 py-3 grid grid-cols-8 space-x-4 bg-blue-500 hover:bg-blue-500 cursor-pointer mx-4">
                                            <div class="col-span-6">
                                                <a href="{{route('categories.edit', $category->id)}}" class="font-bold text-white overflow-ellipsis capitalize text-sm">{{$category->title}}</a>
                                                <p class="overflow-ellipsis w-full font-thin capitalize text-gray-200 text-xs">{{$category->desc}}</p>
                                            </div>
                                            <div class="inline-flex items-center space-x-3 text-white col-span-1">
                                                <a href="{{route('categories.edit', $category->id)}}" class="text-gray-300 hover:text-gray-300 font-bold py-2 px-2">
                                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                                    </svg>
                                                </a>
                                                <form method="POST" action="{{route('categories.destroy', $category->id)}}">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" onclick="return confirm('are you sure want to delete?')" class="text-red-500 hover:text-red-600 font-bold py-2">
                                                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M6 18L18 6M6 6l12 12" />
                                                        </svg>
                                                    </button>
                                                </form>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="md:col-span-2">
                <div class="max-w-7xl mx-auto">
                    <div class="bg-white overflow-hidden shadow-sm sm:rounded-md">
                        <div class="px-4 pt-8 pb-3 bg-white border-b border-gray-200" style="height: 550px;">
                            @if(request()->routeIs('categories.index'))
                                <form action="{{route('categories.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @method('post')
                                    <div class="mb-4 w-full space-y-2">
                                        <label class="block text-sm font-medium text-gray-700">Title</label>
                                        <input class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300" type="text" placeholder="Title..." name="title" />
                                    </div>

                                    <div class="mb-4 space-y-2">
                                        <label class="block text-sm font-medium text-gray-700">Description</label>
                                        <textarea class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300 resize-none" name="desc" cols="30" rows="4" placeholder="Description..."></textarea>
                                    </div>

                                    <div class="flex space-x-3 mb-4 text-sm font-medium">
                                        <div class="flex-auto flex space-x-3">
                                            <button class="w-1/8 py-2 px-4 flex items-center justify-center rounded-md bg-blue-500 text-white" type="submit">Save</button>
                                            <a href="{{route('categories.index')}}" class="w-1/8 py-2 px-4 flex items-center justify-center rounded-md border border-gray-300" type="reset">Cancel</a>
                                        </div>
                                    </div>
                                </form>
                            @else
                                <form action="{{route('categories.update', $edit_category->id)}}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @method('put')
                                    <div class="mb-4 w-full space-y-2">
                                        <label class="block text-sm font-medium text-gray-700">Title</label>
                                        <input class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300" type="text" placeholder="Title..." name="title" value="{{$edit_category->title}}" />
                                    </div>

                                    <div class="mb-4 space-y-2">
                                        <label class="block text-sm font-medium text-gray-700">Description</label>
                                        <textarea class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300 resize-none" name="desc" cols="30" rows="4" placeholder="Description...">{{$edit_category->desc}}</textarea>
                                    </div>

                                    <div class="flex space-x-3 mb-4 text-sm font-medium">
                                        <div class="flex-auto flex space-x-3">
                                            <button class="w-1/8 py-2 px-4 flex items-center justify-center rounded-md bg-blue-500 text-white" type="submit">Update</button>
                                            <a href="{{route('categories.index')}}" class="w-1/8 py-2 px-4 flex items-center justify-center rounded-md border border-gray-300" type="reset">Cancel</a>
                                        </div>
                                    </div>
                                </form>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</x-app-layout>

resources/views/admin/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <div class="flex justify-between mb-4">
                <div class="h-20 w-72 px-6 py-4 rounded-md bg-white border">
                    <div class="grid grid-cols-3">
                        <div class="col-span-2">
                            <h1>{{$new_users->count()}}</h1>
                            <p>Today Users</p>
                        </div>
                        <div class="col-span-1 flex justify-center items-center rounded-full border">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                            </svg>
                        </div>
                    </div>
                </div>

                <div class="h-20 w-72 px-6 py-4 rounded-md bg-white border">
                    <div class="grid grid-cols-3">
                        <div class="col-span-2">
                            <h1>{{$users->count()}}</h1>
                            <p>All Users</p>
                        </div>
                        <div class="col-span-1 flex justify-center items-center rounded-full border">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                            </svg>
                        </div>
                    </div>
                </div>

                <div class="h-20 w-72 px-6 py-4 rounded-md bg-white border">
                    <div class="grid grid-cols-3">
                        <div class="col-span-2">
                            <h1>{{$new_projects->count()}}</h1>
                            <p>Today Projects</p>
                        </div>
                        <div class="col-span-1 flex justify-center items-center rounded-full border">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M8 13v-1m4 1v-3m4 3V8M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
                            </svg>
                        </div>
                    </div>
                </div>

                <div class="h-20 w-72 px-6 py-4 rounded-md bg-white border">
                    <div class="grid grid-cols-3">
                        <div class="col-span-2">
                            <h1>{{$projects->count()}}</h1>
                            <p>All Projects</p>
                        </div>
                        <div class="col-span-1 flex justify-center items-center rounded-full border">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">

                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="grid grid-cols-5">
                        <div class="col-span-3">
                            @include('charts.google-bar-chart')
                        </div>

                        <div class="col-span-2">
                            @include('charts.google-pie-chart')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/project.blade.php
hello word

resources/views/admin/projects.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Projects') }}
        </h2>
    </x-slot>


    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="border-t-4 border-teal-500 rounded-b px-4 py-3 shadow-md bg-red-500 text-white absolute z-50" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Error</p>
                    <p class="text-sm">{{$error}}</p>
                </div>
            </div>
        </div>
        @endforeach
    @endif

    @if(Session::has('success'))
        <div class="border-t-4 border-teal-500 rounded-b px-4 py-3 shadow-md bg-green-500 text-white absolute z-50" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Success</p>
                    <p class="text-sm">{{session('success')}}</p>
                </div>
            </div>
        </div>
    @endif

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <section class="relative bg-blueGray-50">
                <div class="w-full">
                    <div class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded
                    bg-blue-500 text-white">
                        <div class="rounded-t mb-0 px-4 py-3 border-0">
                            <div class="flex flex-wrap items-center">
                                <div class="relative w-full px-4 max-w-full flex-grow flex-1 ">
                                    <div class="flex justify-between">
                                        <h3 class="font-semibold text-lg text-white">All Projects</h3>
                                        <form class="group relative">
                                            <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 -mt-2.5 text-gray-400 pointer-events-none group-focus-within:text-blue-500" aria-hidden="true">
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" />
                                            </svg>
                                            <input class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300 text-gray-500 pl-10" type="text" aria-label="Filter projects" placeholder="Filter projects...">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="block w-full overflow-x-auto ">
                            <table class="items-center w-full bg-transparent border-collapse">
                                <thead>
                                    <tr>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Project</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Status</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Owner</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Members</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Completion </th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700"></th>
                                    </tr>
                                </thead>

                                <tbody class="divide-y">
                                    @foreach($all_projects as $project)
                                        <tr>
                                            <th class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4 text-left flex items-center">
                                                @if($project->image_url == 'N/A')
                                                    <small class="h-12 w-12 font-thin text-xs text-blue-500 bg-white rounded-full border flex justify-center items-center ring-2 ring-white">
                                                        no image
                                                    </small>
                                                @else
                                                    <img src="{{Storage::url($project->image_url)}}" class="h-12 w-12 bg-white rounded-full border object-cover" alt="...">
                                                @endif

                                                <span class="ml-3 font-bold text-white"> {{$project->name}} </span>
                                            </th>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <i class="fas fa-circle text-yellow-500 mr-2"></i>{{$project->status}}</td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                @foreach($all_users as $user)
                                                    @if($user->id == $project->user_id)
                                                        {{$user->name}}
                                                    @endif
                                                @endforeach
                                            </td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <div class="flex">

                                                    <?php
$assigned_users = DB::table('assign_users')
    ->join('users', 'assign_users.user_id', '=', 'users.id')
    ->where('project_id', '=', $project->id)
    ->select('users.*')->get();
?>

                                                @foreach($assigned_users as $user)
                                                    <img src="{{Storage::url($user->avatar)}}" alt="..." class="w-6 h-6 rounded-full border-2 border-blueGray-50 shadow -ml-4 object-cover">
                                                @endforeach

                                                </div>
                                            </td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <div class="flex items-center">
                                                    <span class="mr-2">0%</span>
                                                    <div class="relative w-full">
                                                        <div class="overflow-hidden h-2 text-xs flex rounded bg-white">
                                                            <div style="width: 0%" class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-yellow-500">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>

                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <div class="flex items-center space-x-3">
                                                    <a href="{{route('projects.show', $project->id)}}" class="text-white hover:text-yellow-500">Preview</a>
                                                    <form action="{{route('projects.destroy', $project->id)}}" method="POST">
                                                        @csrf
                                                        @method('delete')
                                                        <input onclick="return confirm('are you sure want to delete?')" class="cursor-pointer text-white hover:text-red-500" type="submit" value="Delete">
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {{$all_projects->links()}}
                </div>

            </section>

        </div>
    </div>
</x-app-layout>