routes/web.php
<?php

use App\Http\Controllers\AdminHomeController;
use App\Http\Controllers\AssignUserController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/login');
})->middleware(['auth']);

Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'admin']], function () {
    // dashboard routes
    Route::resource('/', AdminHomeController::class)->name('*', 'dashboard');

    // projects routes
    Route::resource('/projects', ProjectController::class)->name('*', 'projects');

    // projects category routes
    Route::resource('/categories', CategoryController::class)->name('*', 'categories');

    // users routes
    Route::resource('/users', UserController::class)->name('*', 'users');

    // profile routes
    Route::get('/profile', function () {return view('welcome');})->name('Profile');
});

Route::group(['prefix' => '', 'middleware' => ['auth', 'user']], function () {

    // dashboard routes
    Route::resource('/home', HomeController::class)->name('*', 'home');

    // user routes
    Route::resource('/user', UserController::class)->name('*', 'user');

    // projects routes
    Route::resource('/my/project', ProjectController::class)->name('*', 'project');

    // projects category routes
    Route::resource('/assign', AssignUserController::class)->middleware(['auth'])->name('*', 'assign');
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'avatar',
        'name',
        'email',
        'phone',
        'gender',
        'title',
        'role',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\User;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_users = User::where('id', '!=', Auth::id())->orderBy('updated_at', 'desc')->paginate(5);

        $all_projects = Project::all();

        return view('admin.users', [
            'all_users' => $all_users,
            'all_projects' => $all_projects,
            'title' => 'All Users',
            'desc' => 'This is meta description for all Users',
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user_form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'gender' => ['required', 'string', 'max:255'],
            'title' => ['required', 'string', 'max:255'],
            'role' => ['required', 'string', 'max:255'],
            'password' => ['required', 'confirmed'],
        ]);

        if ($request->hasFile('avatar')) {
            $avatar = Storage::disk('local')->put('avatars', $request->file('avatar'));
            $user = User::create([
                'avatar' => $avatar,
                'name' => $request->name,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'role' => $request->role,
                'password' => Hash::make($request->password),
            ]);
        } else {
            $user = User::create([
                'avatar' => 'N/A',
                'name' => $request->name,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'role' => $request->role,
                'password' => Hash::make($request->password),
            ]);
        }

        event(new Registered($user));

        Auth::login($user);

        return redirect('register')->with('success', 'user successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $my_profile = User::findOrFail($id);

        $my_projects = DB::table('categories')
            ->join('projects', 'categories.id', '=', 'projects.category_id')
            ->where('user_id', '=', Auth::id())
            ->orderBy('projects.created_at', 'desc')
            ->get();

        $assigned_projects = DB::table('assign_users')
            ->join('projects', 'projects.id', '=', 'assign_users.project_id')
            ->where('assign_users.user_id', '=', Auth::id())
            ->orderBy('projects.created_at', 'desc')
            ->select('projects.*')
            ->get();

        return view('profile', [
            'my_profile' => $my_profile,
            'my_projects' => $my_projects,
            'assigned_projects' => $assigned_projects,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit_user = User::findOrFail($id);

        return view('admin.user_form', [
            'edit_user' => $edit_user,
            'title' => ucfirst($edit_user->name),
            'desc' => 'This is meta description for User Edit',
        ]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'fname' => ['required', 'string', 'max:255'],
            'lname' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'gender' => ['string', 'max:1'],
            'title' => ['required', 'string', 'max:255'],
            'phone' => ['string', 'max:255'],
            'current_pass' => ['string', 'max:255'],
        ]);

        if ($request->hasFile('avatar')) {
            $avatar = Storage::disk('public')->put('avatars', $request->file('avatar'));
            $user = User::findOrFail($id)->update([
                'avatar' => $avatar,
                'name' => $request->fname . ' ' . $request->lname,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'password' => $request->filled('new_pass') && $request->filled('confirm_pass') && $request->new_pass == $request->confirm_pass ? Hash::make($request->new_pass) : $request->current_pass,
            ]);
        } else {
            $user = User::findOrFail($id)->update([
                'name' => $request->fname . ' ' . $request->lname,
                'email' => $request->email,
                'gender' => $request->gender,
                'phone' => $request->phone,
                'title' => $request->title,
                'password' => $request->filled('new_pass') && $request->filled('confirm_pass') && $request->new_pass == $request->confirm_pass ? Hash::make($request->new_pass) : $request->current_pass,
            ]);
        }

        dd($request->hasFile('avatar'));

        // event(new Registered($user));

        // Auth::login($user);

        if (Auth::user()->role == 'admin') {
            return redirect('users/' . Auth::id())->with('success', 'user successfully updated!');
        } else {
            return redirect('user/' . Auth::id())->with('success', 'user successfully updated!');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        redirect('admin/users')->with('success', 'user successfully created!');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="overflow-scroll">

                    <div class="grid grid-cols-2 space-x-8">
                        <div class="col-span-1 bg-white border-b border-gray-200 shadow-sm rounded-lg">
                            <div class="flex items-center justify-between bg-blue-500 px-6 py-5">
                                <h3 class="font-semibold text-white">Charts</h3>
                            </div>

                            @include('charts.google-bar-chart')
                        </div>

                        <div class="col-span-1 bg-white border-b border-gray-200 shadow-sm rounded-lg">

                            <section>
                                <header class="bg-white space-y-4 p-4 sm:px-8 sm:py-6 lg:p-4 xl:px-8 xl:py-6">
                                    <div class="flex items-center justify-between">
                                        <h2 class="font-semibold text-gray-900">My Projects</h2>
                                        <a href="{{route('project.index')}}" class="hover:bg-blue-400 group flex items-center rounded-md bg-blue-500 text-white text-xs font-medium px-2 py-3 shadow-sm">
                                            All My Projects
                                        </a>
                                    </div>
                                    <form class="group relative">
                                        <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 -mt-2.5 text-gray-400 pointer-events-none group-focus-within:text-blue-500" aria-hidden="true">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" />
                                        </svg>
                                        <input class="focus:ring-1 focus:ring-blue-500 focus:outline-none w-full text-sm leading-6 text-gray-900 placeholder-gray-400 rounded-md py-2 pl-10 ring-1 ring-gray-200 shadow-sm" type="text" aria-label="Filter projects" placeholder="Filter projects...">
                                    </form>
                                </header>
                                <ul class="p-4 sm:px-8 sm:pt-2 sm:pb-8 lg:p-4 xl:px-8 xl:pt-2 xl:pb-8 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2 gap-4 text-sm leading-6">
                                    <li class="flex">
                                        <a href="{{route('project.create')}}" class="hover:border-blue-500 hover:border-solid hover:bg-white hover:text-blue-500 group w-full flex flex-col items-center justify-center rounded-md border-2 border-dashed border-gray-300 text-sm leading-6 text-gray-900 font-medium py-3 h-28">
                                            <svg class="group-hover:text-blue-500 mb-1 text-gray-400" width="20" height="20" fill="currentColor" aria-hidden="true">
                                            <path d="M10 5a1 1 0 0 1 1 1v3h3a1 1 0 1 1 0 2h-3v3a1 1 0 1 1-2 0v-3H6a1 1 0 1 1 0-2h3V6a1 1 0 0 1 1-1Z" />
                                            </svg>
                                            New project
                                        </a>
                                    </li>
                                    @foreach($my_projects as $project)
                                        <li>
                                            <a href="{{route('project.show', $project->id)}}" class="hover:bg-blue-500 hover:ring-blue-500 hover:shadow-md group rounded-md p-3 bg-white ring-1 ring-gray-200 shadow-sm w-full flex flex-col">
                                                <dl class="grid sm:block lg:grid xl:block grid-cols-2 grid-rows-2 items-center">
                                                    <div>
                                                        <dt class="sr-only">Title</dt>
                                                        <dd class="group-hover:text-white font-semibold text-gray-900">
                                                            {{ucfirst($project->name)}}
                                                        </dd>
                                                    </div>
                                                    <div>
                                                        <dt class="sr-only">Category</dt>
                                                        <dd class="group-hover:text-blue-200">{{ucfirst($project->title)}}</dd>
                                                    </div>
                                                    <div class="col-start-2 row-start-1 row-end-3 sm:mt-4 lg:mt-0 xl:mt-4">
                                                        <dt class="sr-only">Users</dt>
                                                        <dd x-for="user in project.users" class="flex justify-end sm:justify-start lg:justify-end xl:justify-start -space-x-1.5">
                                                            <div class="flex -space-x-1 h-6">
        <?php
$assigned_users = DB::table('assign_users')
    ->join('users', 'assign_users.user_id', '=', 'users.id')
    ->where('project_id', '=', $project->id)
    ->select('users.*')->get();
?>

                                                                @foreach($assigned_users as $user)
                                                                    <img class="inline-block h-6 w-6 rounded-full ring-2 ring-white object-cover" src="{{Storage::url($user->avatar)}}" alt="">
                                                                @endforeach

                                                            </div>
                                                        </dd>
                                                    </div>
                                                </dl>
                                            </a>
                                        </li>
                                    @endforeach

                                </ul>
                            </section>

                        </div>
                    </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/user/projects.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Projects') }}
        </h2>
    </x-slot>


    @if($errors->any())
        @foreach($errors->all() as $error)
        <div class="border-t-4 border-teal-500 rounded-b px-4 py-3 shadow-md bg-red-500 text-white absolute z-50" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Error</p>
                    <p class="text-sm">{{$error}}</p>
                </div>
            </div>
        </div>
        @endforeach
    @endif

    @if(Session::has('success'))
        <div class="border-t-4 border-teal-500 rounded-b px-4 py-3 shadow-md bg-green-500 text-white absolute z-50" role="alert">
            <div class="flex items-center">
                <div class="py-1">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div>
                    <p class="font-bold">Success</p>
                    <p class="text-sm">{{session('success')}}</p>
                </div>
            </div>
        </div>
    @endif

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <section class="grid grid-cols-6 space-x-8">
                <div class="w-full col-span-2">
                    <div class="flex flex-col min-w-0 break-words w-full mb-4 shadow-lg rounded-t bg-blue-500 text-white">
                        <div class="rounded-t mb-0 px-8 py-5 border-0">
                            <h3 class="font-semibold text-base text-white">Projects Assigned To</h3>
                        </div>
                    </div>

                    <div class="divide-y px-8 shadow rounded">
                        @foreach($assigned_projects as $project)

                            <div class="grid grid-cols-5 py-3">
                                <div class="col-span-3">
                                    <h4 class="font-bold text-sm text-gray-600">{{$project->name}}</h4>
                                    <div class="text-xs font-bold text-gray-400">
                                        <span>desc</span>
                                        <span>time</span>
                                    </div>
                                </div>

                                <div class="col-span-2 flex">
                                    <?php
$assigned_users = DB::table('assign_users')
    ->join('users', 'assign_users.user_id', '=', 'users.id')
    ->where('project_id', '=', $project->id)
    ->select('users.*')->get();
?>

                                    @foreach($assigned_users as $user)
                                        <img src="{{Storage::url($user->avatar)}}" alt="..." class="w-6 h-6 rounded-full border-2 border-blueGray-50 object-cover shadow -ml-4">
                                    @endforeach

                                </div>
                            </div>

                        @endforeach
                    </div>
                </div>

                <div class="w-full col-span-4">
                    <div class="relative flex flex-col min-w-0 break-words w-full mb-6 shadow-lg rounded
                    bg-blue-500 text-white">
                        <div class="rounded-t mb-0 px-4 py-3 border-0">
                            <div class="flex flex-wrap items-center">
                                <div class="relative w-full px-4 max-w-full flex-grow flex-1 ">
                                    <div class="flex justify-between items-center">
                                        <h3 class="font-semibold text-base text-white">My Projects</h3>
                                        <div class="flex space-x-3">
                                            <a class="flex text-sm px-3 hover:bg-yellow-500 rounded-md items-center" href="{{route('project.create')}}">
                                                New
                                            </a>
                                            <form class="group relative">
                                                <svg width="20" height="20" fill="currentColor" class="absolute left-3 top-1/2 -mt-2.5 text-gray-400 pointer-events-none group-focus-within:text-blue-500" aria-hidden="true">
                                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" />
                                                </svg>
                                                <input class="focus:ring-indigo-500 focus:border-indigo-500 flex-1 block w-full rounded sm:text-sm border-gray-300 text-gray-500 pl-10" type="text" aria-label="Filter projects" placeholder="Filter projects...">
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="block w-full overflow-x-auto ">
                            <table class="items-center w-full bg-transparent border-collapse">
                                <thead>
                                    <tr>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Project</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Status</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Members</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Date</th>
                                        <th class="px-6 align-middle border border-solid py-3 text-xs uppercase border-l-0 border-r-0 whitespace-nowrap font-semibold text-left bg-blue-800 text-blue-300 border-blue-700">Action</th>
                                    </tr>
                                </thead>

                                <tbody class="divide-y">
                                    @foreach($my_projects as $project)
                                        <tr>
                                            <th class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-sm whitespace-nowrap p-4 text-left flex items-center">
                                                @if($project->image_url == 'N/A')
                                                    <small class="h-12 w-12 font-thin text-xs text-blue-500 bg-white rounded-full border flex justify-center items-center ring-2 ring-white">
                                                        no image
                                                    </small>
                                                @else
                                                    <img src="{{Storage::url($project->image_url)}}" class="h-12 w-12 bg-white rounded-full border object-cover ring-1 ring-white" alt="...">
                                                @endif

                                                <div class="flex flex-col">
                                                    <span class="ml-3 font-bold text-white"> {{ucwords($project->name)}} </span>
                                                    <small class="ml-3 text-gray-300"> {{ucwords($project->name)}} </small>
                                                </div>
                                            </th>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <i class="fas fa-circle text-yellow-500 mr-2"></i>{{$project->status}}</td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <div class="flex">

                                                    <?php
$assigned_users = DB::table('assign_users')
    ->join('users', 'assign_users.user_id', '=', 'users.id')
    ->where('project_id', '=', $project->id)
    ->select('users.*')->get();
?>

                                                    @foreach($assigned_users as $user)
                                                        <img src="{{Storage::url($user->avatar)}}" alt="..." class="w-6 h-6 rounded-full border-2 border-blueGray-50 object-cover shadow -ml-4">
                                                    @endforeach

                                                </div>
                                            </td>
                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <span>{{date('M d, Y', strtotime($project->created_at))}}</span>
                                                <!-- <small>{{date('g:i A', strtotime($project->created_at))}}</small> -->
                                            </td>

                                            <td class="border-t-0 px-6 align-middle border-l-0 border-r-0 text-xs whitespace-nowrap p-4">
                                                <div class="flex items-center space-x-3">
                                                    <a href="{{route('project.show', $project->id)}}" class="text-white hover:text-yellow-500">Preview</a>
                                                    <a href="{{route('project.edit', $project->id)}}" class="text-white hover:text-yellow-500">Edit</a>
                                                    <form action="{{route('project.destroy', $project->id)}}" method="POST">
                                                        @csrf
                                                        @method('delete')
                                                        <input onclick="return confirm('are you sure want to delete?')" class="cursor-pointer text-white hover:text-red-500" type="submit" value="Delete">
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {{$my_projects->links()}}
                </div>

            </section>

        </div>
    </div>
</x-app-layout>